- hosts: webServers
  become: yes
  tasks:
    - name: Update Apt Repo and Installing Apache
      apt:
        name: apache2
        update_cache: yes
        force_apt_get: yes
        
    - name: Start Apache Service
      service:
        name: apache2
        state: started
        
    - name: Transfering Script from Repo to Server
      ansible.builtin.copy:
        src: ./setup.sh
        dest: ~/setup.sh
        mode: '0755' 
        
    - name: Run Script For WebSite
      ansible.builtin.shell: 
        cmd: './setup.sh'
        chdir: ~/
        

